name: Events
version: 1.0.0
main: de.elorise.events.Events
api-version: 1.19
authors: [ lukas ]
commands:
  discord:
    aliases: [dc]
  serverinfo:
    aliases: [serveri]
  fly:
  heal:
    aliases: [heilung]
